name: pyg_2
channels:
  - conda-forge
  - defaults
  - pytorch
dependencies:
  - _python_abi3_support=1.0=hd8ed1ab_2
  - appnope=0.1.4=pyhd8ed1ab_1
  - asttokens=3.0.1=pyhd8ed1ab_0
  - bzip2=1.0.8=h80987f9_6
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - captum=0.7.0=0
  - colorama=0.4.6=pyhd8ed1ab_1
  - comm=0.2.3=pyhe01879c_0
  - contourpy=1.3.3=py312h20e30b6_0
  - cpython=3.12.12=py312hd8ed1ab_1
  - debugpy=1.8.17=py312h56d30c9_0
  - executing=2.2.1=pyhd8ed1ab_0
  - expat=2.7.1=h313beb8_0
  - filelock=3.20.0=py312hca03da5_0
  - fonttools=4.60.1=py312h254cc4a_0
  - freetype=2.13.3=h47d26ad_0
  - fsspec=2025.10.0=py312h7eb115d_0
  - gmp=6.3.0=h313beb8_0
  - gmpy2=2.2.1=py312h5c1b81f_0
  - icu=75.1=hfee45f7_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - ipykernel=7.1.0=pyh5552912_0
  - ipython=9.7.0=pyh53cf698_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jinja2=3.1.6=py312hca03da5_0
  - jpeg=9f=h2f69dba_0
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.9.1=pyhc90fa1f_0
  - krb5=1.21.3=h237132a_0
  - lcms2=2.16=he26ebf3_1
  - lerc=4.0.0=h313beb8_0
  - libabseil=20250512.1=cxx17_hd41c47c_0
  - libblas=3.9.0=1_h9886b1c_netlib
  - libcblas=3.9.0=1_h9886b1c_netlib
  - libcxx=20.1.8=hd7fd590_1
  - libdeflate=1.22=h80987f9_0
  - libedit=3.1.20250104=pl5321hafb1f1b_0
  - libexpat=2.7.1=hec049ff_0
  - libffi=3.4.4=hca03da5_1
  - libgfortran=5.0.0=14_2_0_h6c33f7e_103
  - libgfortran5=14.2.0=h6c33f7e_103
  - libhwloc=2.11.2=default_hbce5d74_1001
  - libiconv=1.18=h23cfdf5_2
  - liblapack=3.9.0=1_h9886b1c_netlib
  - libopenjpeg=2.5.4=haa24f5a_1
  - libpng=1.6.50=h5c318fc_0
  - libprotobuf=6.31.1=h658db43_2
  - libsodium=1.0.20=h99b78c6_0
  - libsqlite=3.51.0=h8adb53f_0
  - libtiff=4.7.1=h367c460_0
  - libtorch=2.8.0=cpu_generic_h853542e_2
  - libuv=1.51.0=h6caf38d_1
  - libwebp-base=1.6.0=h92b2d59_0
  - libxml2=2.13.5=hbbdcc80_0
  - libzlib=1.3.1=h5f15de7_0
  - llvm-openmp=20.1.8=he822017_0
  - llvmlite=0.46.0=py312hc82e5dd_0
  - lz4-c=1.9.4=h313beb8_1
  - markupsafe=3.0.2=py312h80987f9_0
  - matplotlib-base=3.10.6=py312h37b8ce2_1
  - matplotlib-inline=0.2.1=pyhd8ed1ab_0
  - mpc=1.3.1=h80987f9_0
  - mpfr=4.2.1=h80987f9_0
  - mpmath=1.3.0=py312hca03da5_0
  - ncurses=6.5=hee39554_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - networkx=3.5=py312hca03da5_0
  - nomkl=1.0=h5ca1d4c_0
  - numba=0.63.1=py312hadc56cb_0
  - numpy=2.3.5=py312h85ea64e_0
  - openjpeg=2.5.4=h959fc53_1
  - openssl=3.6.0=h5503f6c_0
  - optree=0.14.1=py312h48ca7d4_0
  - packaging=25.0=pyh29332c3_1
  - parso=0.8.5=pyhcf101f3_0
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pip=25.3=pyhc872135_0
  - platformdirs=4.5.0=pyhcf101f3_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - psutil=7.1.3=py312h37e1c23_0
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pybind11=2.10.4=py312h48ca7d4_0
  - pybind11-abi=4=hd3eb1b0_1
  - pybind11-global=2.10.4=py312h48ca7d4_0
  - pygments=2.19.2=pyhd8ed1ab_0
  - pynndescent=0.5.13=pyhd8ed1ab_1
  - pyparsing=3.2.5=py312hca03da5_0
  - python=3.12.8=h89a136b_0_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-gil=3.12.12=hd8ed1ab_1
  - python_abi=3.12=1_cp312
  - pytorch=2.8.0=cpu_generic_py312_h05d1414_2
  - pyzmq=27.1.0=py312hd65ceae_0
  - readline=8.3=h0b18652_0
  - setuptools=80.9.0=py312hca03da5_0
  - six=1.17.0=pyhe01879c_1
  - sleef=3.9.0=hb028509_0
  - sqlite=3.51.0=hab6afd1_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - sympy=1.14.0=py312hca03da5_0
  - tbb=2022.1.0=h9541205_0
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tk=8.6.15=hcd8a7d5_0
  - tornado=6.5.2=py312h4409184_2
  - tqdm=4.67.1=pyhd8ed1ab_1
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing-extensions=4.15.0=py312hca03da5_0
  - typing_extensions=4.15.0=py312hca03da5_0
  - umap-learn=0.5.9.post2=py312h81bd7bf_1
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - wheel=0.45.1=py312hca03da5_0
  - xz=5.6.4=h80987f9_1
  - zeromq=4.3.5=h888dc83_9
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.3.1=h5f15de7_0
  - zstd=1.5.7=h817c040_0
  - pip:
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.2
      - aiosignal==1.4.0
      - attrs==25.4.0
      - certifi==2025.11.12
      - charset-normalizer==3.4.4
      - cycler==0.12.1
      - cython==3.2.1
      - decorator==4.4.2
      - frozenlist==1.8.0
      - idna==3.11
      - joblib==1.5.2
      - kiwisolver==1.4.9
      - matplotlib==3.10.7
      - multidict==6.7.0
      - pandas==2.3.3
      - pillow==12.0.0
      - propcache==0.4.1
      - pyg-lib==0.5.0+pt28
      - pytz==2025.2
      - pyyaml==6.0.3
      - requests==2.32.5
      - scikit-learn==1.7.2
      - scipy==1.16.3
      - seaborn==0.13.2
      - torch-cluster==1.6.3
      - torch-geometric==2.7.0
      - torch-geometric-temporal==0.56.2
      - torch-scatter==2.1.2
      - torch-sparse==0.6.18
      - torch-spline-conv==1.2.2
      - torchsummary==1.5.1
      - tzdata==2025.2
      - urllib3==2.5.0
      - xgboost-cpu==3.1.2
      - xxhash==3.6.0
      - yarl==1.22.0
prefix: /opt/miniconda3/envs/pyg_2
