device: null # if null, it automatically sets the available device. (cuda | mps | cpu)

edge:
  is_mi_based: True # if 0, it generates fully connected edge index.
  n_neighbors: 3 # NOTE: cv result of n_neighbors: 3
  top_k: 6
  threshold: 0.01
  pruning_ratio: 0.5
  return_edge_attr: False # CAUTION: potential error when set to True

model:
  name: gin
  params:
    embedding_dim: 32
    gin_dim: 32
    gin_layer_num: 3
    train_eps: True

train:
  batch_size: 32
  learning_rate: 0.001 # optimizer learning rate
  epochs: 100
  seed: 1
  binary: True
  train_ratio: 0.7
  val_ratio: 0.15
  test_ratio: 0.15
  num_workers: 0
  lr_scheduler_patience: 10
  early_stopping_patience: 15
  decision_threshold: 0.5
  cv: True
  n_folds: 5