device: null # if null, it automatically sets the available device. (cuda | mps | cpu)

edge:
  is_mi_based: True # if 0, it generates fully connected edge index.
  n_neighbors: 3 # NOTE: cv result of n_neighbors: 3
  top_k: 6
  threshold: 0.01
  pruning_ratio: 0.5
  return_edge_attr: False # CAUTION: potential error when set to True

model:
  name: gin
  params:
    embedding_dim: 32
    gin_hidden_channel: 32
    gin_1_layers: 2
    gin_hidden_channel_2: 32
    gin_2_layers: 2
    train_eps: True
    los_embedding_dim: 8
    gate_hidden_ch: null # Hidden_dim of GatedFusion, If set to None, it defaults to in_dim, which is gin_hidden_channel * 3

train:
  batch_size: 32
  learning_rate: 0.001 # optimizer learning rate
  epochs: 100
  seed: 42  
  binary: True
  train_ratio: 0.7
  val_ratio: 0.15
  test_ratio: 0.15
  num_workers: 0
  lr_scheduler_patience: 5
  early_stopping_patience: 10
  dropout_p: 0.2
  decision_threshold: 0.5


