device: null # if null, it automatically sets the available device. (cuda | mps | cpu)

edge:
  is_mi_based: True # if 0, it generates fully connected edge index.
  n_neighbors: 5 # NOTE: cv result of n_neighbors: 3
  top_k: 6
  threshold: 0.0
  pruning_ratio: 0.3
  return_edge_attr: False # CAUTION: potential error when set to True
  edge_cached: False
  cache_path: "./src/data/mi/gin_mi_dict_1.pickle"

model:
  name: gin
  params:
    embedding_dim: 64
    gin_dim: 96
    gin_layer_num: 4
    train_eps: True

train:
  batch_size: 128
  learning_rate: 0.0004799804630214713 # optimizer learning rate
  epochs: 100
  seed: 1
  binary: True
  train_ratio: 0.70
  val_ratio: 0.15
  test_ratio: 0.15
  num_workers: 3
  lr_scheduler_patience: 5
  early_stopping_patience: 10
  decision_threshold: 0.5
  optimizer: "adam"
  weight_decay: 0.0003
  cv: False
  n_folds: 5
  ig_label: False