model:
  name: xgboost
  params:
    col_info: null

train:
  binary: True
  tree_method: hist
  n_estimators: 100
  learning_rate: 0.1
  max_depth: 5
  eval_metric: logloss # mlogloss recommended when binary == False (multi-label classification)
  seed: 4
  train_ratio: 0.7
  val_ratio: 0.15
  test_ratio: 0.15
  batch_size: 32
  num_workers: 0
  do_cross_validation: True
  cv_random_or_grid: True # True for random, False for grid
  cv: True
  n_folds: 5

device: null


# python -m src.main --config configs/xgboost.yaml