device: null

model:
  name: xgboost
  params:
    col_info: null

train:
  binary: True
  tree_method: hist
  n_estimators: 100
  learning_rate: 0.1
  max_depth: 5
  min_child_weight: 1
  gamma: 0.0
  subsample: 0.8
  colsample_bytree: 0.8
  reg_alpha: 0.0
  reg_lambda: 1.0
  eval_metric: logloss # mlogloss recommended when binary == False (multi-label classification)
  seed: 1
  train_ratio: 0.7
  val_ratio: 0.15
  test_ratio: 0.15
  batch_size: 32
  num_workers: 0
  do_cross_validation: False
  cv_random_or_grid: False # True for random, False for grid
  cv: False # k fold cv
  n_folds: 5
  
  
  